build: allow selection of qt5 or qt6, and try to auto-detect
We'll try to auto-detect which Qt version to use, and how to run the
necessary qt build tools (moc, uic, rcc).

Closes issue #43.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6,6 +6,11 @@ PREFIX=/usr/local
 OPT=yes
 DBG=yes
 X11=yes
+qtmoc=moc
+qtuic=uic
+qtrcc=rcc
+qtver=
+qttooldir=
 
 for arg; do
 	case "$arg" in
@@ -24,6 +29,13 @@ for arg; do
 	--disable-debug)
 		DBG=no;;
 
+	--qt5)
+		qtver=5;;
+	--qt6)
+		qtver=6;;
+	--qt-tooldir=*)
+		qttooldir=`echo $arg | sed 's/--qt-tooldir=//; s/\/$//'`;;
+
 	--help)
 		echo 'usage: ./configure [options]'
 		echo 'options:'
@@ -32,15 +44,69 @@ for arg; do
 		echo '  --disable-opt: disable speed optimizations'
 		echo '  --enable-debug: include debugging symbols (default)'
 		echo '  --disable-debug: do not include debugging symbols'
+		echo '  --qt5: use Qt 5.x (default)'
+		echo '  --qt6: use Qt 6.x'
+		echo '  --qt-tooldir=<path>: location of moc, uic, and rcc, if not in PATH'
 		echo 'all invalid options are silently ignored'
 		exit 0
 		;;
 	esac
 done
 
+# if qt version was not specified, try to auto-detect it
+if [ -z "$qtver" ]; then
+	if pkg-config --exists Qt6Widgets; then
+		qtver=6
+	else
+		qtver=5
+	fi
+fi
+
+check_moc_version()
+{
+	if [ -n "$qttooldir" ]; then
+		qtmoc=$qttooldir/moc
+		qtuic=$qttooldir/uic
+		qtrcc=$qttooldir/rcc
+	fi
+	mocver=`$qtmoc --version 2>/dev/null | sed 's/moc //; s/\..*//'`
+}
+
+# check moc presence and version
+check_moc_version
+if [ $? != 0 -o "$mocver" != "$qtver" ]; then
+	# moc not found, if tooldir was specified, panic
+	if [ -n "$qttooldir" ]; then
+		echo "can't find moc in the specified Qt tooldir: $qttooldir" >&2
+		exit 1
+	fi
+	# try to find moc
+	mocpath=`find /usr/lib/qt$qtver -name moc | head -1`
+	if [ -z "$mocpath" ]; then
+		echo "failed to find Qt tools (moc,uic,rcc), use --qt-tooldir=<path> to specify their location" >&2
+		exit 1
+	fi
+	qttooldir=`dirname $mocpath`
+	check_moc_version
+fi
+if [ "$mocver" != "$qtver" ]; then
+	echo "Using Qt $qtver, but found moc from Qt $mocver." >&2
+	echo "Use --qt-tooldir=<path> to specify the location of the Qt $qtver tools (moc,uic,rcc)" >&2
+	exit 1
+fi
+
+if [ "$qtver" -ge 6 ]; then
+	cstd=c++17
+else
+	cstd=c++11
+fi
+
+
 echo "  prefix: $PREFIX"
 echo "  optimize for speed: $OPT"
 echo "  include debugging symbols: $DBG"
+echo "  using Qt $qtver"
+[ -n "$qttooldir" ] && echo "  Qt tool path: $qttooldir"
 echo
 
 # create Makefile
@@ -54,6 +120,12 @@ fi
 if [ "$OPT" = 'yes' ]; then
 	echo 'opt = -O3' >>Makefile
 fi
+
+echo "qtmoc = $qtmoc" >>Makefile
+echo "qtuic = $qtuic" >>Makefile
+echo "qtrcc = $qtrcc" >>Makefile
+echo "cflags_qt = -std=${cstd} `pkg-config --cflags Qt${qtver}Core Qt${qtver}Gui Qt${qtver}Widgets`" >>Makefile
+echo "libs_qt = `pkg-config --libs Qt${qtver}Core Qt${qtver}Gui Qt${qtver}Widgets`" >>Makefile
 
 if [ -n "$CFLAGS" ]; then
 	echo "add_cflags = $CFLAGS" >>Makefile
